---
- name: Create OS info file
  hosts: localhost
  gather_facts: yes  #collect facts about the target hosts before executing any tasks
  tasks:
    - name: Determine OS name
      set_fact:
        file_name: "{{ ansible_distribution }}"

    - name: Create your_target_groupOS info file
      ansible.builtin.copy:
        content: "{{ ansible_facts | to_nice_json }}"
        dest: "/home/einfochips/Downloads/{{ file_name }}.txt"
